language: r
os: linux
dist: xenial

jobs:
  include:
    - dist: bionic
      r: release
      apt_packages: libpoppler-cpp-dev
    - dist: xenial
      r: devel
      apt_packages: libpoppler-cpp-dev
    - os: osx
      r: release

cache: packages
